### ISSUE TITLE
marked处理问题

### ISSUE THREAD

**Issue by petitspois** [linxixuan/linxixuan-blog#1]
marked and highlight 是 render 的时候做的处理。我是在入库前做的处理。现在有个问题，提取的时候把html标签都显示了。mongoose 有tohtml方法之类的吗？

**Comment by linxixuan** [comment]
严格的说，marked不算是只在render的时候做处理。你把它理解为一个function，输入是markdown格式的字符串，输出则是html片段的字符串。
我不清楚mongoose会不会有tohtml的方法，但是我想应该不太可能有。因为mongoose做的工作就是抽象了一个DB modal。
如果你需要在入库前做tohtml的工作，建议你先将markdown转成html，再把结果存到数据库中去。
至于highlight，也是一样，highlight只是marked里的一个配置项。你可以去marked的仓库看看文档:)

**Comment by petitspois** [comment]
解决了。template问题, thanks
